### ISSUE TITLE
Add Gradle Wrapper

### ISSUE THREAD

**Issue by pvepamb1** [vkoul1/Modern-Trading-Platform#1]
I was wondering if it'd be a good idea to add a gradle wrapper to this project. That way, we could ensure all of us are using the right version, and upgrading gradle would be simple as changing a version in the properties file.

Here's some more info:
https://docs.gradle.org/current/userguide/gradle_wrapper.html

Let me know what you guys think

**Comment by vkoul1** [comment]
Ya go ahead. I was also looking for that. It would be great if you could add it.
